name: NodeSeek签到

on:
  schedule:
    - cron: '23 7 * * *'  # 每天7点23分运行

jobs:
  run-signin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install curl_cffi requests

    - name: Run the sign-in script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        NS_COOKIE: ${{ secrets.NS_COOKIE }}
        TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      run: |
        python Signin-NS.py
